services:
  db:
    image: mysql:8.0
    container_name: croabboard-db
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-croabboard}
      MYSQL_USER: ${MYSQL_USER:-croabboard}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-croabboard}
    volumes:
      - db_data:/var/lib/mysql
      - ./crobboard.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    container_name: croabboard-backend
    network_mode: host
    environment:
      NODE_ENV: production
      PORT: 5000
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-croabboard}
      MYSQL_USER: ${MYSQL_USER:-croabboard}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-croabboard}
      SESSION_SECRET: ${SESSION_SECRET:-super-secret}
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:5000/api}
    container_name: croabboard-frontend
    network_mode: host
    depends_on:
      - backend

volumes:
  db_data:
  backend_uploads: